name: Unkle Fester the Docker image builder and python tester

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main

jobs:
  everything:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build  Docker image
      run: docker build -t misube/lab5 .

    - name: Push image to hub
      run: docker push misube/lab5

    - name: Run tests
      run: docker run misube/lab5